//
// Price.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Price: Codable {

    public var USD: PriceInfo?
    public var AUD: PriceInfo?
    public var BRL: PriceInfo?
    public var CAD: PriceInfo?
    public var CHF: PriceInfo?
    public var CLP: PriceInfo?
    public var CNY: PriceInfo?
    public var DKK: PriceInfo?
    public var EUR: PriceInfo?
    public var GBP: PriceInfo?
    public var INR: PriceInfo?
    public var ISK: PriceInfo?
    public var JPY: PriceInfo?
    public var KRW: PriceInfo?
    public var NZD: PriceInfo?
    public var PLN: PriceInfo?
    public var RUB: PriceInfo?
    public var SEK: PriceInfo?
    public var SGD: PriceInfo?
    public var THD: PriceInfo?
    public var TWD: PriceInfo?

    public init(USD: PriceInfo?, AUD: PriceInfo?, BRL: PriceInfo?, CAD: PriceInfo?, CHF: PriceInfo?, CLP: PriceInfo?, CNY: PriceInfo?, DKK: PriceInfo?, EUR: PriceInfo?, GBP: PriceInfo?, INR: PriceInfo?, ISK: PriceInfo?, JPY: PriceInfo?, KRW: PriceInfo?, NZD: PriceInfo?, PLN: PriceInfo?, RUB: PriceInfo?, SEK: PriceInfo?, SGD: PriceInfo?, THD: PriceInfo?, TWD: PriceInfo?) {
        self.USD = USD
        self.AUD = AUD
        self.BRL = BRL
        self.CAD = CAD
        self.CHF = CHF
        self.CLP = CLP
        self.CNY = CNY
        self.DKK = DKK
        self.EUR = EUR
        self.GBP = GBP
        self.INR = INR
        self.ISK = ISK
        self.JPY = JPY
        self.KRW = KRW
        self.NZD = NZD
        self.PLN = PLN
        self.RUB = RUB
        self.SEK = SEK
        self.SGD = SGD
        self.THD = THD
        self.TWD = TWD
    }


}

